#!/bin/sh
pnpm exec vitest run --config config/vitest.unit.config.ts 'src/lib/' --reporter=dot --passWithNoTests
pnpm --filter bridgeport-ui exec vitest run 'src/lib/' --reporter=dot --passWithNoTests
